#!/usr/bin/env bash
# clean_seed_data.sh — Remove ALL seeded/test data from VAF and Obsidian vault.
# Run once on your Mac: bash scripts/clean_seed_data.sh

set -e
DIR="$(cd "$(dirname "$0")/.." && pwd)"
DATA="$DIR/data"

echo "🧹 Cleaning VAF seed data from: $DATA"

# ── Insight JSON files ─────────────────────────────────────────────────────
find "$DATA/education/notes/insights" -name "ins_seed_*.json"      -delete 2>/dev/null && echo "  ✅ Removed ins_seed_* insights"
find "$DATA/education/notes/insights" -name "ins_2026-03-21_*.json" -delete 2>/dev/null
find "$DATA/education/notes/insights" -name "ins_2026-03-22_*.json" -delete 2>/dev/null && echo "  ✅ Removed 2026-03-21/22 test insights"

# ── Old raw RSS notes ──────────────────────────────────────────────────────
rm -f "$DATA/education/notes/2026-03-21_raw.json"
rm -f "$DATA/education/notes/2026-03-22_raw.json"
rm -f "$DATA/education/index.json"
echo "  ✅ Removed old RSS notes"

# ── Old briefings and summaries ────────────────────────────────────────────
rm -f "$DATA/briefings/2026-03-21.json"
find "$DATA/summaries" -name "2026-03-21.json" -delete 2>/dev/null
echo "  ✅ Removed stale briefings/summaries"

# ── Obsidian vault — remove any VAF-generated seed notes ──────────────────
# Read vault path from .env
VAULT=""
if [ -f "$DIR/.env" ]; then
    VAULT=$(grep "VAF_OBSIDIAN_VAULT_DIR" "$DIR/.env" | cut -d'=' -f2- | tr -d '"' | tr -d "'")
fi

if [ -n "$VAULT" ] && [ -d "$VAULT" ]; then
    echo ""
    echo "🗂  Cleaning Obsidian vault: $VAULT"

    # Remove any notes auto-generated by VAF that contain the seed markers
    find "$VAULT" -name "*.md" -exec grep -l "ins_seed_\|ins_2026-03-21\|ins_2026-03-22\|Auto-generated by Vaishali Agent Force" {} \; 2>/dev/null | while read -r f; do
        echo "  🗑  Removing: $(basename "$f")"
        rm -f "$f"
    done

    echo "  ✅ Obsidian vault cleaned"
else
    echo ""
    echo "  ⚠️  Obsidian vault not found at: '$VAULT'"
    echo "     Check VAF_OBSIDIAN_VAULT_DIR in .env"
fi

echo ""
echo "✅ Done — clean slate. Drop a real link in Telegram to start building real data."
